IF 
InParty(Myself)
Global("RE_ValygarToB","GLOBAL",0)
!Global("O#XanMoonbladeExtinguished","GLOBAL",3)
Gender(Player1,FEMALE)
OR(4) 
Race(Player1,ELF)
Race(Player1,HALF_ELF)
Race(Player1,HUMAN)
Race(Player1,HALFLING)
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
RealSetGlobalTimer("RE_ValygarToBTimer","GLOBAL",1)
SetGlobal("RE_ValygarToB","GLOBAL",2)
END

IF
InParty(Myself)
Global("RE_ValygarToB","GLOBAL",3)
GlobalGT("TalkedSarMel01","GLOBAL",0)
Global("Chapter","GLOBAL",%bg2_chapter_8%)
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
RealSetGlobalTimer("RE_ValygarToBTimer","GLOBAL",1)
SetGlobal("RE_ValygarToB","GLOBAL",4)
END

IF
InParty(Myself)
Global("RE_ValygarToB","GLOBAL",5)
AreaCheck("AR6400")
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
RealSetGlobalTimer("RE_ValygarToBTimer","GLOBAL",1)
SetGlobal("RE_ValygarToB","GLOBAL",6)
END

IF
InParty(Myself)
Global("RE_ValygarToB","GLOBAL",7)
GlobalGT("WraithPunish","GLOBAL",0)
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
RealSetGlobalTimer("RE_ValygarToBTimer","GLOBAL",1)
SetGlobal("RE_ValygarToB","GLOBAL",8)
END

IF
InParty(Myself)
Global("RE_ValygarToB","GLOBAL",19)
Dead("balth")
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
RealSetGlobalTimer("RE_ValygarToBTimer","GLOBAL",1)
SetGlobal("RE_ValygarToB","GLOBAL",20)
END

IF
GlobalLT("RE_ValygarToB","GLOBAL",21)
RealGlobalTimerExpired("RE_ValygarToBTimer","GLOBAL")
InParty(Myself)
!AreaType(DUNGEON)
!Global("Chapter","GLOBAL",%bg2_chapter_10%)
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
OR(4)
Global("RE_ValygarToB","GLOBAL",9)
Global("RE_ValygarToB","GLOBAL",11)
Global("RE_ValygarToB","GLOBAL",13)
Global("RE_ValygarToB","GLOBAL",15)
THEN
RESPONSE #100
IncrementGlobal("RE_ValygarToB","GLOBAL",1)
END

IF
GlobalLT("RE_ValygarToB","GLOBAL",21)
RealGlobalTimerExpired("RE_ValygarToBTimer","GLOBAL")
InParty(Myself)
!AreaType(DUNGEON)
!Global("Chapter","GLOBAL",%bg2_chapter_10%)
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
OR(9)
Global("RE_ValygarToB","GLOBAL",2)
Global("RE_ValygarToB","GLOBAL",4)
Global("RE_ValygarToB","GLOBAL",6)
Global("RE_ValygarToB","GLOBAL",8)
Global("RE_ValygarToB","GLOBAL",10)
Global("RE_ValygarToB","GLOBAL",12)
Global("RE_ValygarToB","GLOBAL",14)
Global("RE_ValygarToB","GLOBAL",16)
Global("RE_ValygarToB","GLOBAL",20)
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END
